# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7
matrix:
  include:
  - os: osx
    language: generic
    env:
    - TOXENV=py27
  - os: osx
    language: generic
    env:
    - TOXENV=py34
  - os: osx
    language: generic
    env:
    - TOXENV=py35
  - os: osx
    language: generic
    env:
    - TOXENV=py36
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    PIP=pip2
  else
    PIP=pip
  fi
- $PIP install -U tox-travis

# command to run tests, e.g. python setup.py test
script: tox
