# Config file for automatic testing at travis-ci.org

language: python
python:
  - 2.7
  - 3.6
  - 3.5
  - 3.4
env:
  matrix:
    include:
    - os: osx
      language: generic
      env:
      - PIP=pip2
  global:
  - PIP=pip
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: $PIP install -U tox-travis

# command to run tests, e.g. python setup.py test
script: tox
