package:
  name: {{ cookiecutter.project_slug }}
  version: {{ cookiecutter.project_version }}

source:
  url: {{ cookiecutter.url }}

requirements:
  build:
    - setuptools
  host:
    - python

test:
  imports:
    - {{ cookiecutter.project_slug }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

about:
  home: {{ cookiecutter.home }}
  license: {{ cookiecutter.package_license }}
  license_file: LICENSE
  summary: {{ cookiecutter.project_short_description }}
  dev_url: {{ cookiecutter.dev_url }}
